/**
 * template.js — the headless document shell for single-page docs.
 *
 * Deliberately dependency-free: the knowledge base's own test fixture generator
 * (scripts/setup-test-apps.mjs) imports this module so the fixture and the real
 * action agree on the document shell without pulling the action's node_modules
 * into the knowledge base build.
 *
 * Everything emitted here must satisfy contract/HEADLESS_RULES.md:
 *   • data-kb-headless="true" on <html>
 *   • no <base> tag, all asset paths relative
 *   • no site-level <header>, no sidebar, no theme toggle
 *   • light only — no dark palette, no localStorage theme bootstrap
 */

/** Relative path (from a doc's index.html) to its stylesheet. */
export const CSS_PATH = 'assets/doc.css';
/** Relative path to the vendored mermaid bundle (only written when needed). */
export const MERMAID_PATH = 'assets/mermaid.min.js';
/** Relative path to the mermaid init script (only written when needed). */
export const MERMAID_INIT_PATH = 'assets/mermaid-init.js';

/** Escapes a string for use in an HTML text node or double-quoted attribute. */
export function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Stylesheet ────────────────────────────────────────────────────────────────

/**
 * The stylesheet shipped inside every doc directory.
 *
 * Two jobs:
 *   1. Declare the canonical design tokens so the artifact also looks right when
 *      opened standalone (in the knowledge base the same :root block is declared by
 *      src/styles/knowledge-base.css with identical values).
 *   2. Style the prose, scoped to `.kb-doc`, so nothing leaks into the masthead
 *      or into a host application when the page is embedded as a web fragment.
 *
 * Colours/radii follow contract/STYLE_GUIDE.md, including its dark slate code
 * blocks — the *page* is light-only, code blocks are not.
 */
export const DOC_CSS = `/* Generated by AbsaOSS/knowledge-base/actions/publish-single-page-docs — do not edit. */

/* ── Design tokens (contract/STYLE_GUIDE.md) ──────────────────────────────── */
:root {
  --color-kb-25:  #fdf8f9;
  --color-kb-50:  #f8eaee;
  --color-kb-100: #f0d0da;
  --color-kb-400: #d4547a;
  --color-kb-500: #af144b;
  --color-kb-600: #93103f;
  --color-kb-950: #1b0e12;

  --font-sans: Inter, 'Noto Sans', ui-sans-serif, system-ui, sans-serif;
  --font-mono: 'SF Mono', 'Fira Code', 'Fira Mono', ui-monospace, monospace;

  --bg-page:       var(--color-kb-25);
  --bg-card:       #ffffff;
  --bg-strong:     #f9fafb;
  --bg-subtle:     #f3f4f6;
  --border:        #e5e7eb;
  --border-subtle: #f3e7eb;
  --text-heading:  var(--color-kb-950);
  --text-body:     #4b5563;
  --text-muted:    #6b7280;

  --radius-sm: 6px;
  --radius-md: 12px;
  --radius-lg: 16px;
  --radius-xl: 20px;
}

body { margin: 0; font-family: var(--font-sans); color: var(--text-body); }

/* ── Reading column ───────────────────────────────────────────────────────── */
/* Standalone only. Inside the knowledge base the .kb-single-page wrapper owns the
   measure, so this stays a max-width rather than a fixed layout. */
.kb-doc {
  max-width: 50rem;
  margin: 0 auto;
  padding: 2.5rem 1.5rem 5rem;
  font-size: 1rem;
  line-height: 1.75;
  color: var(--text-body);
  overflow-wrap: break-word;
}
.kb-single-page > .kb-doc { padding: 0; max-width: none; }

/* ── Lede (rendered when the markdown has no top-level heading) ───────────── */
.kb-doc-lede { margin: 0 0 2.5rem; }
.kb-doc-lede p { font-size: 1.125rem; color: var(--text-muted); margin: 0.5rem 0 0; }

/* ── Headings ─────────────────────────────────────────────────────────────── */
.kb-doc h1, .kb-doc h2, .kb-doc h3,
.kb-doc h4, .kb-doc h5, .kb-doc h6 {
  color: var(--text-heading);
  font-weight: 700;
  letter-spacing: -0.02em;
  line-height: 1.25;
  scroll-margin-top: 2rem;
}
.kb-doc h1 { font-size: 2.25rem; margin: 0 0 1.25rem; }
.kb-doc h2 { font-size: 1.5rem;  margin: 3rem 0 1rem; padding-bottom: 0.5rem; border-bottom: 1px solid var(--border); }
.kb-doc h3 { font-size: 1.1875rem; margin: 2.25rem 0 0.75rem; }
.kb-doc h4 { font-size: 1rem;    margin: 1.75rem 0 0.5rem; }
.kb-doc h5, .kb-doc h6 { font-size: 0.9375rem; margin: 1.5rem 0 0.5rem; }

/* Heading anchors — revealed on hover, invisible to the reading eye otherwise */
.kb-doc .kb-anchor {
  color: var(--text-hint, #9ca3af);
  text-decoration: none;
  margin-left: 0.4rem;
  opacity: 0;
  transition: opacity 0.2s;
}
.kb-doc h1:hover .kb-anchor, .kb-doc h2:hover .kb-anchor,
.kb-doc h3:hover .kb-anchor, .kb-doc h4:hover .kb-anchor { opacity: 1; }

/* ── Flow ─────────────────────────────────────────────────────────────────── */
.kb-doc p  { margin: 0 0 1.25rem; }
.kb-doc ul, .kb-doc ol { margin: 0 0 1.25rem; padding-left: 1.5rem; }
.kb-doc li { margin: 0.375rem 0; }
.kb-doc li > ul, .kb-doc li > ol { margin: 0.375rem 0; }
.kb-doc hr { border: 0; border-top: 1px solid var(--border); margin: 2.5rem 0; }
.kb-doc img, .kb-doc video { max-width: 100%; height: auto; border-radius: var(--radius-md); }

.kb-doc a { color: var(--color-kb-500); text-decoration: none; }
.kb-doc a:hover { color: var(--color-kb-600); text-decoration: underline; }

.kb-doc strong { color: var(--text-heading); font-weight: 600; }

/* ── Task lists (GFM) ─────────────────────────────────────────────────────── */
.kb-doc .contains-task-list { list-style: none; padding-left: 0.25rem; }
.kb-doc .task-list-item { display: flex; align-items: flex-start; gap: 0.5rem; }
.kb-doc .task-list-item-checkbox { margin-top: 0.45rem; accent-color: var(--color-kb-500); }

/* ── Blockquotes ──────────────────────────────────────────────────────────── */
.kb-doc blockquote {
  margin: 0 0 1.25rem;
  padding: 0.75rem 1rem;
  border-left: 4px solid var(--color-kb-500);
  background: var(--bg-subtle);
  border-radius: 0 var(--radius-sm) var(--radius-sm) 0;
  color: var(--text-body);
}
.kb-doc blockquote > :last-child { margin-bottom: 0; }

/* ── Tables ───────────────────────────────────────────────────────────────── */
.kb-doc .kb-table-wrap { overflow-x: auto; margin: 0 0 1.5rem; }
.kb-doc table {
  border-collapse: collapse;
  width: 100%;
  font-size: 0.9375rem;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  overflow: hidden;
}
.kb-doc thead { background: var(--bg-strong); }
.kb-doc th, .kb-doc td { padding: 0.625rem 0.875rem; text-align: left; border-bottom: 1px solid var(--border); }
.kb-doc th { color: var(--text-heading); font-weight: 600; }
.kb-doc tbody tr:last-child td { border-bottom: 0; }
.kb-doc tbody tr:hover { background: var(--bg-strong); }

/* ── Code ─────────────────────────────────────────────────────────────────── */
.kb-doc code {
  font-family: var(--font-mono);
  background: var(--bg-strong);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 1px 5px;
  font-size: 0.85em;
}
.kb-doc pre.kb-code {
  margin: 0 0 1.5rem;
  padding: 1rem 1.125rem;
  background: #0f172a;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  overflow-x: auto;
}
.kb-doc pre.kb-code code {
  background: none;
  border: 0;
  padding: 0;
  font-size: 0.8125rem;
  line-height: 1.7;
  color: #e2e8f0;
}

/* highlight.js token colours, tuned for the slate code surface above */
.kb-doc .hljs-comment, .kb-doc .hljs-quote { color: #64748b; font-style: italic; }
.kb-doc .hljs-keyword, .kb-doc .hljs-selector-tag, .kb-doc .hljs-built_in { color: #c4b5fd; }
.kb-doc .hljs-string, .kb-doc .hljs-regexp, .kb-doc .hljs-addition { color: #86efac; }
.kb-doc .hljs-number, .kb-doc .hljs-literal, .kb-doc .hljs-deletion { color: #fca5a5; }
.kb-doc .hljs-title, .kb-doc .hljs-title.class_, .kb-doc .hljs-title.function_,
.kb-doc .hljs-section, .kb-doc .hljs-name { color: #93c5fd; }
.kb-doc .hljs-attr, .kb-doc .hljs-attribute, .kb-doc .hljs-variable,
.kb-doc .hljs-template-variable, .kb-doc .hljs-property { color: #fcd34d; }
.kb-doc .hljs-type, .kb-doc .hljs-meta, .kb-doc .hljs-symbol, .kb-doc .hljs-bullet { color: #67e8f9; }
.kb-doc .hljs-emphasis { font-style: italic; }
.kb-doc .hljs-strong { font-weight: 700; }

/* ── Mermaid ──────────────────────────────────────────────────────────────── */
/* Pre-render the source is hidden; mermaid swaps in an <svg> in its place. */
.kb-doc pre.mermaid {
  margin: 0 0 1.5rem;
  padding: 1.25rem;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  text-align: center;
  overflow-x: auto;
  font-family: var(--font-mono);
  font-size: 0.8125rem;
  color: var(--text-muted);
}
/* margin-inline:auto, not the parent's text-align. Mermaid sets display:block on
   the <svg> it swaps in, and a block box ignores text-align — so a diagram
   narrower than the column sat flush left. */
.kb-doc pre.mermaid svg { max-width: 100%; height: auto; display: block; margin-inline: auto; }

/* ── Footnotes (GFM) ──────────────────────────────────────────────────────── */
.kb-doc .footnotes {
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--border);
  font-size: 0.875rem;
  color: var(--text-muted);
}
.kb-doc .footnotes hr { display: none; }
`;

// ── Mermaid bootstrap ─────────────────────────────────────────────────────────

/**
 * Init script for the vendored mermaid bundle.
 *
 * Vendored rather than loaded from a CDN: knowledge base pages are re-hosted inside
 * a web fragment behind a strict CSP, so every asset a doc needs must live in its
 * own artifact. `startOnLoad` is off because the knowledge base swaps pages with
 * Astro's ClientRouter — rendering is driven from both the initial load and the
 * `astro:page-load` event instead.
 *
 * Shipped as a FILE rather than inlined.
 *
 * It used to be an inline <script> in the document. That is the one thing that
 * makes a meaningful Content-Security-Policy impossible: allowing it means
 * `script-src 'unsafe-inline'`, which allows every injected script too, and
 * hashing it would hard-couple the knowledge base's nginx config to this action's
 * exact bytes — bundles published by an older version would then break. As a
 * file it is covered by `script-src 'self'` and nothing has to know about it.
 */
export const MERMAID_INIT_JS = `/* Generated by AbsaOSS/knowledge-base/actions/publish-single-page-docs — do not edit. */
(function () {
  var render = function () {
    if (!window.mermaid) return;
    var nodes = document.querySelectorAll('pre.mermaid:not([data-processed])');
    if (!nodes.length) return;
    window.mermaid.initialize({
      startOnLoad: false,
      theme: 'base',
      securityLevel: 'strict',
      fontFamily: 'Inter, Noto Sans, ui-sans-serif, system-ui, sans-serif',
      themeVariables: {
        primaryColor: '#f8eaee', primaryTextColor: '#1b0e12', primaryBorderColor: '#af144b',
        lineColor: '#93103f', secondaryColor: '#f0d0da', tertiaryColor: '#fdf8f9'
      }
    });
    try { window.mermaid.run({ nodes: nodes }); } catch (e) { /* leave the source visible */ }
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', render);
  else render();
  document.addEventListener('astro:page-load', render);
})();
`;

/** The two external <script> tags a mermaid-using doc needs. No inline script. */
export function mermaidBootstrap() {
  return `<script src="${MERMAID_PATH}"></script>
<script src="${MERMAID_INIT_PATH}"></script>`;
}

// ── Document ──────────────────────────────────────────────────────────────────

/**
 * Builds a complete headless HTML document for one doc.
 *
 * @param {object}  doc
 * @param {string}  doc.title        - human-readable page title
 * @param {string}  doc.description  - catalog description, also the meta description
 * @param {string}  doc.bodyHtml     - rendered markdown (already HTML)
 * @param {boolean} [doc.usesMermaid] - true when the body contains a mermaid block
 * @param {boolean} [doc.hasHeading]  - true when the body already opens with an <h1>
 * @returns {string}
 */
export function renderDocument({ title, description, bodyHtml, usesMermaid = false, hasHeading = true }) {
  // Only synthesise a lede when the author's markdown has no <h1> of its own —
  // duplicating the title above an existing heading reads as a bug.
  const lede = hasHeading ? '' : `  <header class="kb-doc-lede">
    <h1>${escapeHtml(title)}</h1>
    <p>${escapeHtml(description)}</p>
  </header>
`;

  return `<!DOCTYPE html>
<html lang="en" data-kb-headless="true">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="description" content="${escapeHtml(description)}">
<link rel="stylesheet" href="${CSS_PATH}">
</head>
<body>
<article class="kb-doc">
${lede}${bodyHtml.trim()}
</article>
${usesMermaid ? mermaidBootstrap() + '\n' : ''}</body>
</html>
`;
}
