import { createHash } from 'node:crypto';
const STOP = new Set('a an and are as at be by can create do does for from get how i if in into is it like make me my of on or please the this to use using want what whats when where which who why will with would you your'.split(' '));
const hash = (value) => createHash('sha256').update(value).digest('hex').slice(0, 8);
export const normalize = (value) => String(value ?? '').normalize('NFKC').replace(/([a-z\d])([A-Z])/g, '$1 $2').toLowerCase();
export const tokenize = (value) => { const original = String(value ?? '').normalize('NFKC'); const joined = original.replace(/([a-z\d])([A-Z])/g, '$1 $2').replace(/[^\p{L}\p{N}]+/gu, ' ').trim(); const tokens = joined.toLowerCase().split(/\s+/).filter((word) => word.length > 1 || /^\d+$/.test(word)); const compact = original.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, ''); return compact && !tokens.includes(compact) ? [compact, ...tokens] : tokens; };
export function stem(word) { let value = word; for (const suffix of ['ations', 'ation', 'ions', 'ion', 'ings', 'ing', 'ers', 'er']) if (value.endsWith(suffix) && value.length - suffix.length >= 4) return value.slice(0, -suffix.length); if (value.endsWith('ied') && value.length > 6) return value.slice(0, -3) + 'y'; if (value.endsWith('ies') && value.length > 6) return value.slice(0, -3) + 'y'; for (const suffix of ['ed', 'es', 's', 'e']) if (value.endsWith(suffix) && value.length - suffix.length >= 4 && !(suffix === 's' && value.endsWith('ss'))) return value.slice(0, -suffix.length); return value; }
const distance = (a, b) => { const row = [...Array(b.length + 1).keys()]; for (let i = 1; i <= a.length; i += 1) { let previous = row[0]++; for (let j = 1; j <= b.length; j += 1) { const old = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, previous + (a[i - 1] === b[j - 1] ? 0 : 1)); previous = old; } } return row[b.length]; };
const cursor = (offset, fingerprint) => Buffer.from(JSON.stringify({ v: 1, h: fingerprint, o: offset })).toString('base64url');
const parseCursor = (value, fingerprint) => { if (!value) return 0; try { const data = JSON.parse(Buffer.from(value, 'base64url').toString()); if (data.v !== 1 || data.h !== fingerprint || !Number.isInteger(data.o) || data.o < 0) throw Error(); return data.o; } catch { throw new Error('Invalid cursor'); } };
export function createIndex(corpus) { const apps = new Map(corpus.apps.map((app) => [app.slug, app])); const terms = new Set(); const fields = corpus.documents.map((document) => { const app = apps.get(document.app); const pieces = [document.title, document.description, app?.name ?? '', document.tags.join(' '), document.text]; const words = tokenize(pieces.join(' ')).map(stem); words.forEach((word) => terms.add(word)); return { document, app, words, textWords: tokenize(document.text).map(stem) }; }); return { corpus, apps, fields, terms }; }
function termsFor(index, query) { const raw = tokenize(query).map(stem); let queryTerms = raw.filter((word) => !STOP.has(word)); if (!queryTerms.length) queryTerms = raw; const expansions = []; for (const word of queryTerms) { if (index.terms.has(word)) { expansions.push([word, 1]); continue; } let split; for (let i = 2; i < word.length - 1; i += 1) if (index.terms.has(word.slice(0, i)) && index.terms.has(word.slice(i))) { split = [word.slice(0, i), word.slice(i)]; break; } if (split) expansions.push(...split.map((part) => [part, 1])); else { const max = word.length >= 8 ? 2 : word.length >= 5 ? 1 : 0; expansions.push(...[...index.terms].filter((term) => distance(word, term) <= max).sort().slice(0, 3).map((term) => [term, .5])); } } return expansions; }
const publicDoc = (document, app, publicOrigin) => ({ uri: document.uri, title: document.title, app: document.app, appName: app?.name ?? document.app, route: document.route, ...(publicOrigin ? { url: new URL(document.route, publicOrigin).toString() } : {}) });
export function search(index, params, { publicOrigin } = {}) { const terms = termsFor(index, params.query); if (!terms.length) throw new Error('Query has no searchable terms'); const eligible = index.fields.filter(({ document }) => (!params.app || document.app === params.app) && (!params.tag || document.tags.some((tag) => tag.toLowerCase() === params.tag.toLowerCase()))); const ranked = eligible.map(({ document, app, words, textWords }) => { let score = 0, hits = 0; for (const [term, weight] of terms) { const count = words.filter((word) => word === term).length; if (count) { hits += 1; score += weight * (count + (tokenize(document.title).map(stem).includes(term) ? 4 : 0)); } } if (!score) return null; const section = document.sections.find((item) => tokenize(item.heading).map(stem).some((word) => terms.some(([term]) => term === word))) ?? document.sections[0]; const content = section ? document.text.slice(section.start, section.end) : document.text; const first = Math.max(0, [...terms].map(([term]) => content.toLowerCase().indexOf(term)).find((n) => n >= 0) ?? 0); let excerpt = content.slice(Math.max(0, first - 120), Math.max(0, first - 120) + 400).replace(/\s+/g, ' ').trim(); if (first > 120) excerpt = `…${excerpt}`; if (content.length > first + 280) excerpt += '…'; return { ...publicDoc(document, app, publicOrigin), ...(section ? { section: { heading: section.heading, anchor: section.anchor } } : {}), excerpt, score: Number((score * (1 + .5 * hits / terms.length)).toFixed(4)) }; }).filter(Boolean).sort((a, b) => b.score - a.score || a.uri.localeCompare(b.uri)); const fingerprint = hash(`${index.corpus.contentHash}|${params.query}|${params.app ?? ''}|${params.tag ?? ''}`); const offset = parseCursor(params.cursor, fingerprint), limit = params.limit ?? 8; return { query: params.query, total: ranked.length, results: ranked.slice(offset, offset + limit), ...(offset + limit < ranked.length ? { nextCursor: cursor(offset + limit, fingerprint) } : {}) }; }
export function list(index, params = {}, { publicOrigin } = {}) { const items = index.fields.filter(({ document }) => (!params.app || document.app === params.app) && (!params.tag || document.tags.some((tag) => tag.toLowerCase() === params.tag.toLowerCase())) && (!params.title || document.title.toLowerCase().includes(params.title.toLowerCase()))).map(({ document, app }) => ({ ...publicDoc(document, app, publicOrigin), description: document.description, tags: document.tags, mimeType: document.mimeType, size: document.size })); const fingerprint = hash(`${index.corpus.contentHash}|${params.app ?? ''}|${params.tag ?? ''}|${params.title ?? ''}`), offset = parseCursor(params.cursor, fingerprint), limit = params.limit ?? 50; return { total: items.length, documents: items.slice(offset, offset + limit), ...(offset + limit < items.length ? { nextCursor: cursor(offset + limit, fingerprint) } : {}) }; }
export function readDocument(index, { uri, offset = 0, maxChars = 20000 }, { publicOrigin } = {}) { const item = index.fields.find(({ document }) => document.uri === uri); if (!item) throw new Error(`Unknown document URI: ${uri}. Use search_documents or list_documents to find valid URIs.`); const { document, app } = item; let end = Math.min(document.text.length, offset + maxChars); if (end < document.text.length && /[\uD800-\uDBFF]/.test(document.text[end - 1]) && /[\uDC00-\uDFFF]/.test(document.text[end])) end -= 1; const nextOffset = end < document.text.length ? end : undefined; return { ...publicDoc(document, app, publicOrigin), mimeType: 'text/markdown', offset, totalChars: document.text.length, text: document.text.slice(offset, end), ...(nextOffset ? { nextOffset } : {}), truncated: Boolean(nextOffset) }; }
export const cursorFor = cursor; export const parseCursorFor = parseCursor;
